import { Album } from '../../albums/Albums';
import { TreeNode } from '../TreeNode';

export const albums: Album[] = [
  {
    id: 'album1',
    title: 'Archives/Photos/2010/Dogs',
    productUrl: 'www.google.com/album/1',
    coverPhotoBaseUrl: 'www.google.com/album/1/cover',
    mediaItemsCount: 10,
  },
  {
    id: 'album2',
    title: 'Archives/Photos/2010/Cats',
    productUrl: 'www.google.com/album/2',
    coverPhotoBaseUrl: 'www.google.com/album/2/cover',
    mediaItemsCount: 20,
  },
  {
    id: 'album3',
    title: 'Archives/Photos/2009/Cars',
    productUrl: 'www.google.com/album/3',
    coverPhotoBaseUrl: 'www.google.com/album/3/cover',
    mediaItemsCount: 2,
  },
  {
    id: 'album4',
    title: 'Archives/Photos/2009/Houses',
    productUrl: 'www.google.com/album/4',
    coverPhotoBaseUrl: 'www.google.com/album/4/cover',
    mediaItemsCount: 1,
  },
  {
    id: 'album5',
    title: 'Unsorted Photos',
    productUrl: 'www.google.com/album/5',
    coverPhotoBaseUrl: 'www.google.com/album/5/cover',
    mediaItemsCount: 150,
  },
  {
    id: 'album6',
    productUrl: 'www.google.com/album/6',
    coverPhotoBaseUrl: 'www.google.com/album/6/cover',
    mediaItemsCount: 5,
  },
];

export const expectedTree: TreeNode = {
  id: 'mocked-uuid-value',
  title: 'Home',
  coverPhotoBaseUrls: [],
  numPhotos: 0,
  totalMediaItemsCount: 0,
  totalAlbumsCount: 0,
  isAlbum: false,
  childNodes: [
    {
      id: 'mocked-uuid-value',
      title: 'Archives',
      coverPhotoBaseUrls: [
        'www.google.com/album/1/cover',
        'www.google.com/album/2/cover',
        'www.google.com/album/3/cover',
        'www.google.com/album/4/cover',
      ],
      totalMediaItemsCount: 33,
      totalAlbumsCount: 4,
      numPhotos: 0,
      isAlbum: false,
      childNodes: [
        {
          id: 'mocked-uuid-value',
          title: 'Photos',
          coverPhotoBaseUrls: [
            'www.google.com/album/1/cover',
            'www.google.com/album/2/cover',
            'www.google.com/album/3/cover',
            'www.google.com/album/4/cover',
          ],
          totalMediaItemsCount: 33,
          totalAlbumsCount: 4,
          numPhotos: 0,
          isAlbum: false,
          childNodes: [
            {
              id: 'mocked-uuid-value',
              title: '2009',
              coverPhotoBaseUrls: [
                'www.google.com/album/3/cover',
                'www.google.com/album/4/cover',
              ],
              totalMediaItemsCount: 3,
              totalAlbumsCount: 2,
              numPhotos: 0,
              isAlbum: false,
              childNodes: [
                {
                  id: 'mocked-uuid-value',
                  title: 'Cars',
                  coverPhotoBaseUrls: ['www.google.com/album/3/cover'],
                  totalMediaItemsCount: 2,
                  totalAlbumsCount: 1,
                  childNodes: [],
                  numPhotos: 2,
                  isAlbum: true,
                  albumId: 'album3',
                },
                {
                  id: 'mocked-uuid-value',
                  title: 'Houses',
                  coverPhotoBaseUrls: ['www.google.com/album/4/cover'],
                  totalMediaItemsCount: 1,
                  totalAlbumsCount: 1,
                  childNodes: [],
                  numPhotos: 1,
                  isAlbum: true,
                  albumId: 'album4',
                },
              ],
            },
            {
              id: 'mocked-uuid-value',
              title: '2010',
              coverPhotoBaseUrls: [
                'www.google.com/album/1/cover',
                'www.google.com/album/2/cover',
              ],
              totalMediaItemsCount: 30,
              totalAlbumsCount: 2,
              numPhotos: 0,
              isAlbum: false,
              childNodes: [
                {
                  id: 'mocked-uuid-value',
                  title: 'Dogs',
                  coverPhotoBaseUrls: ['www.google.com/album/1/cover'],
                  totalMediaItemsCount: 10,
                  totalAlbumsCount: 1,
                  childNodes: [],
                  numPhotos: 10,
                  isAlbum: true,
                  albumId: 'album1',
                },
                {
                  id: 'mocked-uuid-value',
                  title: 'Cats',
                  coverPhotoBaseUrls: ['www.google.com/album/2/cover'],
                  totalMediaItemsCount: 20,
                  totalAlbumsCount: 1,
                  childNodes: [],
                  numPhotos: 20,
                  isAlbum: true,
                  albumId: 'album2',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'mocked-uuid-value',
      title: 'Unsorted Photos',
      coverPhotoBaseUrls: ['www.google.com/album/5/cover'],
      totalMediaItemsCount: 150,
      totalAlbumsCount: 1,
      numPhotos: 150,
      isAlbum: true,
      albumId: 'album5',
      childNodes: [],
    },
  ],
};
