##################################################################
# A Github action used to deploy the web app
# More info at https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
##################################################################
name: Deploy web app
on:
  push:
    branches: [main]

jobs:
  deploy-app:
    name: Deploy to Netify
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
      NG_APP_GOOGLE_CLIENT_ID: ${{ secrets.NG_APP_PROD_GOOGLE_CLIENT_ID }}
      NG_APP_GOOGLE_CLIENT_SECRET: ${{ secrets.NG_APP_PROD_GOOGLE_CLIENT_SECRET }}
      NG_APP_GOOGLE_REDIRECT_URL: ${{ secrets.NG_APP_PROD_GOOGLE_REDIRECT_URL }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies and angular
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Deploy the app to Netify
        run: |
          curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
